package com.lin.ninisoul

object MealData {
    val meals = listOf(
        Meal(1, "Ugali Nyama Choma", "Maize meal served with grilled roasted meat"),
        Meal(2, "Pilau na Kachumbari", "Spiced rice served with a fresh tomato and onion salad"),
        Meal(3, "Githeri Special", "Boiled maize and beans cooked with vegetables and spices"),
        Meal(4, "Mukimo na Nyama", "Mashed potatoes, maize and greens served with meat stew"),
        Meal(5, "Wali wa Nazi na Samaki", "Coconut rice served with fried or stewed fish"),
        Meal(6, "Chapati na Kuku", "Soft flatbread served with chicken stew"),
        Meal(7, "Matumbo na Ugali", "Slow-cooked tripe stew served with maize meal"),
        Meal(8, "Biryani ya Nyama", "Fragrant spiced rice layered with beef"),
        Meal(9, "Mahindi na Nyama", "Boiled maize served with a rich meat stew"),
        Meal(10, "Samaki wa Kupaka", "Fish cooked in a coconut and spice sauce, coastal style"),
        Meal(11, "Mutura na Kachumbari", "Traditional Kenyan sausage served with tomato salad"),
        Meal(12, "Irio na Nyama", "Mashed potatoes, maize, beans and greens with meat"),
        Meal(13, "Kienyeji Chicken Stew", "Free-range chicken slow cooked in a traditional stew"),
        Meal(14, "Ugali Omena", "Maize meal served with small silver fish in tomato sauce"),
        Meal(15, "Managu na Ugali", "Traditional nightshade greens served with maize meal"),
        Meal(16, "Ndengu na Wali", "Green gram stew served with steamed rice"),
        Meal(17, "Chapati na Maharagwe", "Soft flatbread served with red beans in coconut sauce"),
        Meal(18, "Mbaazi za Nazi", "Pigeon peas cooked in coconut sauce, a coastal favorite"),
        Meal(19, "Sukuma Wiki na Nyama", "Collard greens cooked with bits of beef"),
        Meal(20, "Tilapia na Ugali", "Whole fried tilapia served with maize meal"),
        Meal(21, "Beef Stew na Rice", "Slow cooked beef stew served with steamed rice"),
        Meal(22, "Goat Curry na Chapati", "Spiced goat curry served with soft flatbread"),
        Meal(23, "Kuku wa Kupaka", "Chicken cooked in a creamy coconut sauce"),
        Meal(24, "Ugali Mrenda na Mursik", "Maize meal with mrenda greens, Kalenjin style with fermented milk"),
        Meal(25, "Kunde na Ugali", "Cowpea leaves cooked in a light stew with maize meal"),
        Meal(26, "Nyama ya Kupaka na Wali", "Coconut-spiced meat served with rice"),
        Meal(27, "Mokimo na Kuku", "Mashed greens and potatoes served with chicken"),
        Meal(28, "Ugali Terere", "Maize meal served with amaranth leaves stew"),
        Meal(29, "Pilau ya Kuku", "Spiced rice cooked together with tender chicken"),
        Meal(30, "Kachumbari na Nyama Choma", "Roasted meat served with a fresh vegetable salad"),
        Meal(31, "Fish Pilau", "Spiced rice cooked with chunks of fresh fish"),
        Meal(32, "Ugali Mchicha", "Maize meal served with local spinach stew"),
        Meal(33, "Rice na Maharagwe ya Nazi", "Steamed rice served with coconut-flavored beans"),
        Meal(34, "Beef Stew na Chapati", "Rich beef stew served with soft flatbread"),
        Meal(35, "Samaki wa Kuchoma", "Whole grilled fish, often served with kachumbari"),
        Meal(36, "Maharagwe na Mahindi", "Beans cooked with maize, a simple farm classic"),
        Meal(37, "Ugali na Liver Stew", "Maize meal served with a spiced liver stew"),
        Meal(38, "Chapati na Beef Stew", "Soft flatbread served with hearty beef stew"),
        Meal(39, "Wali wa Nazi na Kuku", "Coconut rice served with chicken stew"),
        Meal(40, "Mukimo na Maharagwe", "Mashed potatoes, maize and greens served with beans"),
        Meal(41, "Ugali Ndengu", "Maize meal served with green gram stew"),
        Meal(42, "Nyama na Chips", "Grilled meat served with crispy fried potato chips"),
        Meal(43, "Kuku na Chips", "Fried or stewed chicken served with potato chips"),
        Meal(44, "Samosa na Chai", "Crispy spiced pastries served with hot tea"),
        Meal(45, "Ugali Managu na Samaki", "Maize meal with nightshade greens and fish"),
        Meal(46, "Chapati na Ndengu", "Soft flatbread served with green gram stew"),
        Meal(47, "Rice na Ndengu", "Steamed rice served with green gram stew"),
        Meal(48, "Goat Stew na Ugali", "Slow-cooked goat stew served with maize meal"),
        Meal(49, "Beef Biryani", "Fragrant rice cooked with spiced beef and potatoes"),
        Meal(50, "Coastal Fish Curry na Wali", "Fish curry in coconut sauce served with rice"),
        Meal(51, "Ugali Kunde na Samaki", "Maize meal with cowpea leaves and fish")
    )
}